@startuml

header GSI/FAIR 08.07.2022
footer Deployment Diagram Potiboard Webflux, A. Bloch-Späth, M.Stein
title Reference Implementation with Spring WebFlux

' legend top right
'   ARM-based MC Teensy 4.1 (Arduino) or STM32
' endlegend

node tcl100 #lightgreen;line:black;text:black
node concentratorPC #lightblue;line:black;text:black
node microprocessor #lightblue;line:black;text:black
node encoder #lightblue;line:black;text:black

microprocessor *-- encoder : GPIO
concentratorPC -- microprocessor : USB-Serial or USB-HID or USB-MIDI
tcl100 -- concentratorPC : Network, e.g. Webflux

@enduml
