@startuml

header GSI/FAIR 08.07.2022
footer System/Network Diagram Potiboard 1., A. Bloch-Späth, M.Stein
title Reference Implementation with USB-serial and Spring WebFlux

 legend top right
   ARM-based MC Teensy 4.1 (Arduino) or STM32
 endlegend

node tcl100 #aliceblue;line:blue;line.dotted;text:blue
node concentratorPC
node microprocessor
node encoder
microprocessor *-- encoder : Serial
concentratorPC -- microprocessor : USB Serial
tcl100 -- concentratorPC : Network

@enduml
