@startuml

header GSI/FAIR 03.11.2022
footer Deployment Diagram Potiboard USB, A. Bloch-Späth, M.Stein
title USB based encoder counter transmission

' legend top right
'   ARM-based MC Teensy 4.1 (Arduino) or STM32
' endlegend

node tcl1000 #lightgreen;line:black;text:black
node microController #lightblue;line:black;text:black
node encoder #lightblue;line:black;text:black
microController *-- encoder : GPIO
tcl1000 -- microController : USB-Serial, USB-HID, USB-Midi
@enduml
