@startuml

header GSI/FAIR 06.11.2022
footer System/Network Diagram Potiboard 2., A. Bloch-Späth, M.Stein
title Implementation with ZeroMQ or other messaging libraries

 legend top right
   Raspberry PI or MC Teensy 4.1 (Arduino)
 endlegend

nwdiag {
  network GPIO {
    group {
      color = "lightblue";
       Encoder_1;
       Encoder_2;
       Encoder_n;
       MicroController;
    }

    color = "gray"
    Encoder_1 [shape = control];
    Encoder_2 [shape = control];
    Encoder_n [shape = control];
    MicroController [shape = component];
  }

  network Network {
    group {
      color = "lightgreen";
      PotiboardApp;
    }
    group {
      color = "orange";
      MQTTServer;
    }
  ACC_Net [shape = cloud];
      PotiboardApp [shape = node, address = ZeroMQ/MQTT];
      MQTTServer [shape = node, address = MQTT];
      MicroController [address = ZeroMQ/MQTT];
  }
}
@enduml
