@startuml

header GSI/FAIR 07.11.2022
footer System/Network Diagram Potiboard 1., A. Bloch-Späth, M.Stein
title Reference Implementation with USB-Serial and Spring WebFlux

 legend top right
   ARM-based MC Teensy 4.1 (Arduino) or Raspberry PI Pico
 endlegend

nwdiag {
  network GPIO {
    group {
      color = "lightblue";
       Encoder_1;
       Encoder_2;
       Encoder_n;
      MicroController;
      EncoderPositionsServerPC;
    }
    color = "gray"
    Encoder_1 [shape = control];
    Encoder_2 [shape = control];
    Encoder_n [shape = control];
    MicroController [shape = component];
    MicroController -- EncoderPositionsServerPC;
    EncoderPositionsServerPC [shape = node, address = USB-Serial];
  }

  network Network {
    ACC_Net [shape = cloud];
    EncoderPositionsServerPC [shape = node, address = WebFlux];
    PotiboardApp [shape = node, address = WebFlux];
    group {
      color = "lightgreen";
      PotiboardApp;
    }
  }
}
@enduml

