@startuml

header GSI/FAIR 06.11.2022
footer System/Network Diagram Potiboard 2., A. Bloch-Späth, M.Stein
title Implementation with ZeroMQ or other messaging libraries

 legend top right
   Raspberry PI or MC Teensy 4.1 (Arduino)
 endlegend

nwdiag {
  network GPIO {
    group {
      color = "lightblue";
       encoder_1;
       encoder_2;
       encoder_n;
       microController;
    }

    color = "gray"
    encoder_1 [shape = control];
    encoder_2 [shape = control];
    encoder_n [shape = control];
    microController [shape = component];
  }

  network Network {
    group {
      color = "lightgreen";
      potiboardApp;
    }
    group {
      color = "orange";
      MQTTServer;
    }
  acc_net [shape = cloud];
      potiboardApp [shape = node, address = ZeroMQ/MQTT];
      MQTTServer [shape = node, address = MQTT];
      microController [address = ZeroMQ/MQTT];
  }
}
@enduml
